-- Generated by DB Script Generator
-- Template : postgresql_head_line.sql
-- Head     : {{headTable}}
-- Line     : {{lineTable}}

CREATE OR REPLACE PROCEDURE {{procName}}(
    -- ── transaction control ────────────────────────────────────────────────
    INOUT pio_trno              integer,
    IN    pi_opflag             character varying,
    INOUT pio_line_no           integer[],

    -- ── audit / context ────────────────────────────────────────────────────
    IN    pi_operation_date     timestamp without time zone,
    IN    pi_{{context_col}}    integer,
    IN    pi_enter_user_id      integer,
    IN    pi_enter_desc         character varying,

    -- ── head business columns ──────────────────────────────────────────────
{{business_parameters}}

    -- ── line business columns (parallel arrays) ────────────────────────────
{{line_array_parameters}},

    -- ── outputs ────────────────────────────────────────────────────────────
    INOUT pi_opid               character varying,
    INOUT pi_error              character varying
)
LANGUAGE plpgsql
AS $procedure$

DECLARE
    lv_trno         INTEGER;
    lv_opid         VARCHAR(10);
    lv_error        VARCHAR(4000);
    lv_newval       VARCHAR(4000);
    lv_oldval       VARCHAR(4000);
    lv_cnt          INTEGER;
    lv_opdate       DATE    := COALESCE(pi_operation_date, CURRENT_DATE)::DATE;
    cnt             RECORD;
    rec             RECORD;
    lv_err_no       VARCHAR(4000);
    lv_err_at_line  TEXT;
    lv_err_desc     VARCHAR(4000);
    j               INTEGER;
    lv_del_cnt      INTEGER := 0;

BEGIN

    lv_opid := fn_getopid(pi_opflag);

    /* ================================================================
       INSERT  (pi_opflag = 'N')
    ================================================================ */
    IF pi_opflag = 'N' THEN

        lv_trno := fn_getnextval('{{headTable}}');

        INSERT INTO {{headTable}} (
            {{pk_col}},
            server_sys_date,
            operation_date,
            {{context_col}},
{{insert_business_columns}}
            operation_id,
            enter_user_id,
            enter_desc,
            delete_flag,
            active_flag
        ) VALUES (
            lv_trno,
            CURRENT_TIMESTAMP,
            lv_opdate,
            pi_{{context_col}},
{{insert_business_values}}
            lv_opid,
            pi_enter_user_id,
            pi_enter_desc,
            'N',
            'Y'
        );

        -- Insert line rows from parallel arrays
        INSERT INTO {{lineTable}} (
            {{line_pk_col}},
            server_sys_date,
            operation_date,
            {{context_col}},
            {{pk_col}},
{{line_insert_cols_full}},
            operation_id,
            enter_user_id,
            enter_desc,
            delete_flag,
            active_flag
        )
        SELECT
            fn_getnextval('{{lineTable}}'),
            CURRENT_TIMESTAMP,
            lv_opdate,
            pi_{{context_col}},
            lv_trno,
{{line_insert_vals_new}},
            lv_opid,
            pi_enter_user_id,
            pi_enter_desc,
            'N',
            'Y'
        FROM unnest(
{{line_unnest_params}}
        ) AS u (
{{line_unnest_aliases}}
        );

        CALL pr_operationdet(
            NULL::INTEGER,
            lv_opdate::DATE,
            NULL::VARCHAR,
            NULL::VARCHAR,
            lv_trno::INTEGER,
            '{{head_table_upper}} MAINTENANCE'::VARCHAR,
            'N'::VARCHAR,
            'N'::VARCHAR,
            '{{head_table_upper}}'::VARCHAR,
            '/* TODO: short code e.g. SAH */'::VARCHAR,
            NULL::INTEGER,
            'N'::VARCHAR,
            pi_enter_user_id::INTEGER,
            pi_enter_desc::VARCHAR,
            lv_opid,
            lv_error
        );

        IF lv_error = 'success' THEN
            pio_trno := lv_trno;
            pi_opid  := lv_opid;
            pi_error := 'success';
        ELSE
            pi_opid  := NULL;
            pi_error := lv_error;
        END IF;

    /* ================================================================
       MODIFY  (pi_opflag = 'M')
    ================================================================ */
    ELSIF pi_opflag = 'M' THEN

        -- ── Head: snapshot for change detection ───────────────────────────
        DISCARD TEMP;
        CREATE TEMP TABLE g_{{headTable}} AS
        SELECT * FROM {{headTable}} WHERE 1 = 2;

        INSERT INTO g_{{headTable}} (
            {{pk_col}},
            operation_date,
            {{context_col}},
{{temp_business_columns}}
            operation_id,
            enter_user_id,
            enter_desc,
            delete_flag,
            active_flag
        ) VALUES (
            pio_trno,
            lv_opdate,
            pi_{{context_col}},
{{temp_business_values}}
            lv_opid,
            pi_enter_user_id,
            pi_enter_desc,
            'N',
            'Y'
        );

        CALL pr_operationdet(
            NULL::INTEGER,
            lv_opdate::DATE,
            NULL::VARCHAR,
            NULL::VARCHAR,
            pio_trno::INTEGER,
            '{{head_table_upper}} MAINTENANCE'::VARCHAR,
            'M'::VARCHAR,
            'N'::VARCHAR,
            '{{head_table_upper}}'::VARCHAR,
            '/* TODO: short code e.g. SAH */'::VARCHAR,
            NULL::INTEGER,
            'N'::VARCHAR,
            pi_enter_user_id::INTEGER,
            pi_enter_desc::VARCHAR,
            lv_opid,
            lv_error
        );

        IF lv_error = 'success' THEN
            FOR cnt IN (
                SELECT t.column_name, t.table_name, k.temp_table,
                       k.primary_key_name, t.data_type
                FROM   information_schema.columns t
                INNER  JOIN table_key_master k ON t.table_name = k.table_name
                WHERE  t.table_schema = current_schema
                  AND  t.table_name   = '{{headTable}}'
                  AND  t.column_name IN (
                    SELECT c.field_name FROM caption_details c
                    WHERE  c.table_name   = t.table_name
                      AND  c.modify_allow = 'Y'
                      AND  c.block_modify = 'N'
                  )
            ) LOOP
                IF cnt.data_type NOT IN ('bytea', 'text') THEN
                    EXECUTE 'SELECT ' || cnt.column_name || '::VARCHAR FROM '
                                || cnt.temp_table
                                || ' WHERE {{pk_col}} = ' || pio_trno
                        INTO lv_newval;
                    EXECUTE 'SELECT ' || cnt.column_name || '::VARCHAR FROM '
                                || cnt.table_name
                                || ' WHERE {{pk_col}} = ' || pio_trno
                        INTO lv_oldval;
                    IF COALESCE(TRIM(lv_newval), ' ') <> COALESCE(TRIM(lv_oldval), ' ') THEN
                        INSERT INTO modification_log (
                            mod_log_det_id, transaction_date, branch_mst_id,
                            table_name, field_name, old_value, new_value,
                            primary_key_field, primary_key_id, operation_id,
                            enter_user_id, enter_desc, accepted_rejected_flag
                        ) VALUES (
                            fn_getnextval('modification_log'), lv_opdate, pi_{{context_col}},
                            '{{headTable}}', cnt.column_name, lv_oldval, lv_newval,
                            '{{pk_col}}', pio_trno, lv_opid,
                            pi_enter_user_id, pi_enter_desc, 'P'
                        );
                    END IF;
                END IF;
            END LOOP;

            SELECT COUNT(1) INTO lv_cnt
            FROM   modification_log
            WHERE  operation_id = lv_opid;

            IF COALESCE(lv_cnt, 0) <= 0 THEN
                pi_opid  := NULL;
                pi_error := 'No change in data. Data is identical';
                DISCARD TEMP;
                RETURN;
            END IF;
        END IF;

        -- ── Head: apply update ────────────────────────────────────────────
        UPDATE {{headTable}}
        SET    operation_date       = lv_opdate,
               {{context_col}}      = pi_{{context_col}},
{{update_business_assignments}}
               operation_id         = lv_opid,
               last_edit_user_id    = pi_enter_user_id,
               last_edit_desc       = pi_enter_desc,
               delete_flag          = 'N',
               active_flag          = 'Y'
        WHERE  {{pk_col}} = pio_trno;

        pi_opid := lv_opid;
        DISCARD TEMP;

        -- ── Line: snapshot for change detection ───────────────────────────
        CREATE TEMP TABLE g_{{lineTable}} AS
        SELECT * FROM {{lineTable}} WHERE 1 = 2;

        INSERT INTO g_{{lineTable}} (
            {{line_pk_col}},
            operation_date,
            {{context_col}},
            {{pk_col}},
{{line_insert_cols_full}},
            operation_id,
            enter_user_id,
            enter_desc,
            delete_flag,
            active_flag
        )
        SELECT
            line_no,
            lv_opdate,
            pi_{{context_col}},
            pio_trno,
{{line_insert_vals_new}},
            lv_opid,
            pi_enter_user_id,
            pi_enter_desc,
            'N',
            'Y'
        FROM unnest(
            pio_line_no,
{{line_unnest_params}}
        ) AS u (
            line_no,
{{line_unnest_aliases}}
        );

        CALL pr_operationdet(
            NULL::INTEGER,
            lv_opdate::DATE,
            NULL::VARCHAR,
            NULL::VARCHAR,
            pio_trno::INTEGER,
            '{{line_table_upper}} MAINTENANCE'::VARCHAR,
            'M'::VARCHAR,
            'N'::VARCHAR,
            '{{line_table_upper}}'::VARCHAR,
            '/* TODO: short code e.g. SAL */'::VARCHAR,
            NULL::INTEGER,
            'N'::VARCHAR,
            pi_enter_user_id::INTEGER,
            pi_enter_desc::VARCHAR,
            lv_opid,
            lv_error
        );

        IF lv_error = 'success' THEN
            FOR rec IN (SELECT * FROM g_{{lineTable}}) LOOP

                IF COALESCE(rec.{{line_pk_col}}, 0) > 0 THEN
                    -- ── existing line: change detection ───────────────────
                    FOR cnt IN (
                        SELECT t.column_name, t.table_name, k.temp_table,
                               k.primary_key_name, t.data_type
                        FROM   information_schema.columns t
                        INNER  JOIN table_key_master k ON t.table_name = k.table_name
                        WHERE  t.table_schema = current_schema
                          AND  t.table_name   = '{{lineTable}}'
                          AND  t.column_name IN (
                            SELECT c.field_name FROM caption_details c
                            WHERE  c.table_name   = t.table_name
                              AND  c.modify_allow = 'Y'
                              AND  c.block_modify = 'N'
                          )
                    ) LOOP
                        IF cnt.data_type NOT IN ('bytea', 'text') THEN
                            EXECUTE 'SELECT ' || cnt.column_name || '::VARCHAR FROM '
                                        || cnt.temp_table
                                        || ' WHERE {{line_pk_col}} = ' || rec.{{line_pk_col}}
                                INTO lv_newval;
                            EXECUTE 'SELECT ' || cnt.column_name || '::VARCHAR FROM '
                                        || cnt.table_name
                                        || ' WHERE {{line_pk_col}} = ' || rec.{{line_pk_col}}
                                INTO lv_oldval;
                            IF COALESCE(TRIM(lv_newval), ' ') <> COALESCE(TRIM(lv_oldval), ' ') THEN
                                INSERT INTO modification_log (
                                    mod_log_det_id, transaction_date, branch_mst_id,
                                    table_name, field_name, old_value, new_value,
                                    primary_key_field, primary_key_id, operation_id,
                                    enter_user_id, enter_desc, accepted_rejected_flag
                                ) VALUES (
                                    fn_getnextval('modification_log'), lv_opdate, pi_{{context_col}},
                                    '{{lineTable}}', cnt.column_name, lv_oldval, lv_newval,
                                    '{{line_pk_col}}', rec.{{line_pk_col}}, lv_opid,
                                    pi_enter_user_id, pi_enter_desc, 'P'
                                );
                            END IF;
                        END IF;
                    END LOOP;

                    -- ── existing line: update ─────────────────────────────
                    UPDATE {{lineTable}}
                    SET    operation_date       = lv_opdate,
                           {{context_col}}      = pi_{{context_col}},
                           {{pk_col}}           = pio_trno,
{{line_update_assignments}},
                           operation_id         = lv_opid,
                           last_edit_user_id    = pi_enter_user_id,
                           last_edit_desc       = pi_enter_desc,
                           delete_flag          = rec.delete_flag,
                           active_flag          = rec.active_flag
                    WHERE  {{line_pk_col}} = rec.{{line_pk_col}};

                ELSIF COALESCE(rec.{{line_pk_col}}, 0) = 0 THEN
                    -- ── new line inside modify ────────────────────────────
                    INSERT INTO {{lineTable}} (
                        {{line_pk_col}},
                        server_sys_date,
                        operation_date,
                        {{context_col}},
                        {{pk_col}},
{{line_insert_cols_full}},
                        operation_id,
                        enter_user_id,
                        enter_desc,
                        delete_flag,
                        active_flag
                    ) VALUES (
                        fn_getnextval('{{lineTable}}'),
                        CURRENT_TIMESTAMP,
                        lv_opdate,
                        pi_{{context_col}},
                        pio_trno,
{{line_insert_vals_rec}},
                        lv_opid,
                        pi_enter_user_id,
                        pi_enter_desc,
                        rec.delete_flag,
                        rec.active_flag
                    );
                END IF;

            END LOOP;
        END IF;

        DISCARD TEMP;

    /* ================================================================
       DELETE  (pi_opflag = 'D')
       Soft-deletes specified lines; soft-deletes head when no active
       lines remain.
    ================================================================ */
    ELSIF pi_opflag = 'D' THEN

        DISCARD TEMP;

        FOR j IN 1..array_length(pio_line_no, 1) LOOP
            UPDATE {{lineTable}}
            SET    operation_date   = lv_opdate,
                   delete_flag      = 'Y',
                   active_flag      = 'N',
                   operation_id     = lv_opid,
                   delete_user_id   = pi_enter_user_id,
                   delete_desc      = pi_enter_desc
            WHERE  {{pk_col}}       = pio_trno
              AND  {{line_pk_col}}  = pio_line_no[j];
        END LOOP;

        SELECT COUNT(*)
        INTO   lv_del_cnt
        FROM   {{lineTable}}
        WHERE  active_flag  = 'Y'
          AND  {{pk_col}}   = pio_trno;

        IF COALESCE(lv_del_cnt, 0) = 0 THEN
            UPDATE {{headTable}}
            SET    operation_date   = lv_opdate,
                   delete_flag      = 'Y',
                   active_flag      = 'N',
                   operation_id     = lv_opid,
                   delete_user_id   = pi_enter_user_id,
                   delete_desc      = pi_enter_desc
            WHERE  {{pk_col}} = pio_trno;
        END IF;

    END IF;

    pi_opid  := lv_opid;
    pi_error := COALESCE(pi_error, 'success');

EXCEPTION
    WHEN OTHERS THEN
        DISCARD TEMP;
        GET STACKED DIAGNOSTICS
            lv_err_no      = RETURNED_SQLSTATE,
            lv_err_desc    = PG_EXCEPTION_DETAIL,
            lv_err_at_line = PG_EXCEPTION_CONTEXT;

        CALL pr_insert_errlog(
            NULL::INTEGER,
            '{{headTable}}_line'::VARCHAR,
            lv_err_no::VARCHAR,
            fn_geterror_codedesc(lv_err_no)::VARCHAR,
            pi_enter_user_id::INTEGER,
            NULL::VARCHAR,
            CURRENT_DATE::DATE,
            SUBSTR(lv_err_at_line, STRPOS(lv_err_at_line, ')') + 2)::VARCHAR
        );

        pi_error := 'error,' || lv_err_no || ',' || fn_geterror_codedesc(lv_err_no);

END;
$procedure$;
